"use client";

import { FormEvent, useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000";
type Case = { id: string; title: string; specialty: string; difficulty: string; learning_objectives: string[]; presenting_complaint: string };
type Turn = { role: "learner" | "patient"; text: string };
type Investigation = { id: string; name: string };
type Report = { overall_score: number; scores: Record<string, number>; missed_items: string[]; strengths: string[]; feedback: string };

export default function Home() {
  const [cases, setCases] = useState<Case[]>([]); const [selected, setSelected] = useState<Case | null>(null);
  const [consultationId, setConsultationId] = useState<string | null>(null); const [turns, setTurns] = useState<Turn[]>([]);
  const [text, setText] = useState(""); const [loading, setLoading] = useState(false); const [report, setReport] = useState<Report | null>(null);
  const [error, setError] = useState(""); const [ordered, setOrdered] = useState<string[]>([]); const [investigations, setInvestigations] = useState<Investigation[]>([]);
  useEffect(() => { fetch(`${API}/cases`).then(r => r.json()).then(setCases).catch(() => setError("Cannot reach the API. Start FastAPI on port 8000.")); }, []);
  async function start(c: Case) { setLoading(true); setError(""); try { const r = await fetch(`${API}/consultations`, {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({case_id:c.id})}); const d=await r.json(); setSelected(c); setConsultationId(d.id); setTurns([]); setReport(null); setOrdered([]); setInvestigations(d.investigations || []); } catch { setError("Could not start consultation."); } finally { setLoading(false); } }
  async function send(event: FormEvent) { event.preventDefault(); if (!consultationId || !text.trim()) return; const value=text; setText(""); setLoading(true); try { const r=await fetch(`${API}/consultations/${consultationId}/turns`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:value,input_mode:"text"})}); const d=await r.json(); if(!r.ok) throw Error(d.detail); setTurns(d.consultation.transcript); } catch(e) { setError(e instanceof Error ? e.message : "Turn failed"); } finally { setLoading(false); } }
  async function order(id: string) { if(!consultationId) return; const r=await fetch(`${API}/consultations/${consultationId}/investigations`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({investigation_id:id})}); const d=await r.json(); if(r.ok) { setOrdered([...ordered, `${d.name}: ${d.summary} ${d.interpretation}`]); } else setError(d.detail); }
  async function complete() { if(!consultationId) return; const finalDiagnosis=window.prompt("Final diagnosis:") || ""; const management=(window.prompt("Management plan (comma-separated):") || "").split(",").map(v=>v.trim()).filter(Boolean); const r=await fetch(`${API}/consultations/${consultationId}/complete`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({final_diagnosis:finalDiagnosis,management_plan:management})}); const d=await r.json(); if(r.ok) setReport(d); else setError(d.detail); }
  return <main><header><p className="eyebrow">Fictional educational simulation — not for real patient diagnosis</p><h1>AI Virtual Patient</h1><p>Practice structured clinical consultations with a case-grounded simulated patient.</p></header>
    {!selected ? <section className="grid">{cases.map(c => <article key={c.id}><p className="tag">{c.specialty} · {c.difficulty}</p><h2>{c.title}</h2><p>{c.presenting_complaint}</p><button disabled={loading} onClick={() => start(c)}>Start consultation</button></article>)}</section> : <section className="consultation"><div><button className="back" onClick={() => {setSelected(null);setConsultationId(null);}}>← Cases</button><h2>{selected.title}</h2><p>{selected.presenting_complaint}</p><div className="transcript">{turns.length === 0 && <p className="muted">Ask your first history question.</p>}{turns.map((t,i)=><p key={i} className={t.role}><strong>{t.role === "learner" ? "You" : "Patient"}:</strong> {t.text}</p>)}</div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask a clinical history question…" disabled={loading || !!report}/><button disabled={loading || !!report}>Send</button></form></div><aside><h3>Investigations</h3>{investigations.map(item=><button key={item.id} onClick={()=>order(item.id)} disabled={!!report}>{item.name}</button>)}{ordered.map((item,i)=><p className="result" key={i}>{item}</p>)}<button className="complete" onClick={complete} disabled={!!report}>Complete consultation</button></aside></section>}
    {report && <section className="report"><h2>Evaluation — {report.overall_score}/100</h2><div className="scores">{Object.entries(report.scores).map(([key,value])=><p key={key}><strong>{key.replace("_"," ")}</strong><span>{value}</span></p>)}</div><h3>Strengths</h3><ul>{report.strengths.map(x=><li key={x}>{x}</li>)}</ul><h3>Missed items</h3><ul>{report.missed_items.map(x=><li key={x}>{x}</li>)}</ul><p>{report.feedback}</p></section>}
    {error && <p className="error">{error}</p>}</main>;
}
