"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
type Case = { id: string; title: string; specialty: string; difficulty: string; presenting_complaint: string };
type Turn = { role: "learner" | "patient"; text: string };
type Investigation = { id: string; name: string };
type Report = { overall_score: number; scores: Record<string, number>; missed_items: string[]; strengths: string[]; feedback: string };

export default function Home() {
  const [cases, setCases] = useState<Case[]>([]); const [selected, setSelected] = useState<Case | null>(null);
  const [consultationId, setConsultationId] = useState<string | null>(null); const [turns, setTurns] = useState<Turn[]>([]);
  const [text, setText] = useState(""); const [loading, setLoading] = useState(false); const [report, setReport] = useState<Report | null>(null);
  const [error, setError] = useState(""); const [ordered, setOrdered] = useState<string[]>([]); const [investigations, setInvestigations] = useState<Investigation[]>([]);
  const [phoneNumber, setPhoneNumber] = useState(""); const [callStatus, setCallStatus] = useState("not started");
  const [browserLive, setBrowserLive] = useState(false); const [listening, setListening] = useState(false); const [patientSpeaking, setPatientSpeaking] = useState(false);
  const socket = useRef<WebSocket | null>(null); const recognition = useRef<any>(null); const browserLiveRef = useRef(false); const patientSpeakingRef = useRef(false);

  useEffect(() => { fetch(`${API}/cases`).then(r => r.json()).then(setCases).catch(() => setError("Cannot reach the API. Start FastAPI on port 8000.")); return () => { socket.current?.close(); stopBrowserLive(); }; }, []);
  function setSpeaking(value: boolean) { patientSpeakingRef.current = value; setPatientSpeaking(value); }
  function speak(reply: string) {
    if (!("speechSynthesis" in window)) return;
    window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(reply); utterance.lang = "en-IN";
    utterance.onstart = () => setSpeaking(true); utterance.onend = utterance.onerror = () => setSpeaking(false); window.speechSynthesis.speak(utterance);
  }
  function connectLive(id: string) {
    socket.current?.close(); const wsBase = API ? API.replace(/^http/, "ws") : `${window.location.protocol === "https:" ? "wss" : "ws"}://${window.location.host}`; const ws = new WebSocket(`${wsBase}/consultations/${id}/live`); socket.current = ws;
    ws.onmessage = event => { const data = JSON.parse(event.data); if (data.type === "call_status") setCallStatus(data.status); if (data.type === "transcript_turn") setTurns(prev => [...prev, { role: data.role === "learner" ? "learner" : "patient", text: data.text }]); if (data.type === "investigation_ordered") setOrdered(prev => prev.includes(data.name) ? prev : [...prev, data.name]); if (data.type === "investigation_result") setOrdered(prev => prev.map(x => x === data.name ? `${data.name}: ${data.summary} ${data.interpretation}` : x)); if (data.type === "evaluation_ready") setReport(data.report); };
    ws.onerror = () => setError("Live dashboard connection failed; text mode remains available.");
  }
  async function start(c: Case) { setLoading(true); setError(""); try { const r = await fetch(`${API}/consultations`, {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({case_id:c.id})}); const d=await r.json(); setSelected(c); setConsultationId(d.id); setTurns([]); setReport(null); setOrdered([]); setInvestigations(d.investigations || []); setCallStatus("ready"); connectLive(d.id); } catch { setError("Could not start consultation."); } finally { setLoading(false); } }
  async function dispatchCall() { if (!consultationId || !phoneNumber.trim()) { setError("Enter the patient's E.164 phone number first."); return; } setLoading(true); try { const r = await fetch(`${API}/consultations/${consultationId}/vaani/dispatch`, {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({contact_number: phoneNumber.trim()})}); const d=await r.json(); if (!r.ok) throw Error(d.detail); setCallStatus(`dispatching (${d.call_id})`); } catch (e) { setError(e instanceof Error ? e.message : "Could not dispatch Vaani call"); } finally { setLoading(false); } }
  async function submitTurn(value: string, inputMode: "text" | "browser_live") { if (!consultationId || !value.trim()) return; setLoading(true); try { const r=await fetch(`${API}/consultations/${consultationId}/turns`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:value,input_mode:inputMode})}); const d=await r.json(); if(!r.ok) throw Error(d.detail); if (inputMode === "text") setTurns(d.consultation.transcript); speak(d.reply); } catch(e) { setError(e instanceof Error ? e.message : "Turn failed"); } finally { setLoading(false); } }
  async function send(event: FormEvent) { event.preventDefault(); const value=text; setText(""); await submitTurn(value, "text"); }
  function stopBrowserLive() { browserLiveRef.current = false; setBrowserLive(false); setListening(false); recognition.current?.stop(); recognition.current = null; window.speechSynthesis?.cancel(); setSpeaking(false); }
  function startBrowserLive() {
    if (!consultationId) return; const w = window as unknown as { SpeechRecognition?: new () => any; webkitSpeechRecognition?: new () => any }; const Recognition = w.SpeechRecognition || w.webkitSpeechRecognition;
    if (!Recognition) { setError("Browser live demo needs Chrome or another browser with Web Speech recognition. Type instead if it is unavailable."); return; }
    setError(""); browserLiveRef.current = true; setBrowserLive(true); const instance = new Recognition(); recognition.current = instance; instance.lang = "en-IN"; instance.continuous = true; instance.interimResults = false;
    instance.onstart = () => setListening(true);
    instance.onspeechstart = () => { if (patientSpeakingRef.current) { window.speechSynthesis.cancel(); setSpeaking(false); } };
    instance.onresult = (event: any) => { for (let index = event.resultIndex; index < event.results.length; index += 1) { if (event.results[index].isFinal) { const spoken = event.results[index][0].transcript.trim(); if (spoken) { if (patientSpeakingRef.current) { window.speechSynthesis.cancel(); setSpeaking(false); } void submitTurn(spoken, "browser_live"); } } } };
    instance.onerror = (event: any) => { if (event.error !== "aborted" && event.error !== "no-speech") setError(`Browser microphone error: ${event.error}. Check microphone permission.`); };
    instance.onend = () => { setListening(false); if (browserLiveRef.current) window.setTimeout(() => { try { instance.start(); } catch { /* recognition is already restarting */ } }, 250); };
    instance.start();
  }
  function captureVoice() { const w = window as unknown as { SpeechRecognition?: new () => any; webkitSpeechRecognition?: new () => any }; const Recognition = w.SpeechRecognition || w.webkitSpeechRecognition; if (!Recognition) { setError("Voice capture is unavailable in this browser. Use Chrome or type your question."); return; } const instance = new Recognition(); instance.lang = "en-IN"; instance.onresult = (event: any) => setText(event.results[0][0].transcript); instance.onerror = () => setError("Microphone capture failed. Check browser permission."); instance.start(); }
  async function order(id: string) { if(!consultationId) return; const r=await fetch(`${API}/consultations/${consultationId}/investigations`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({investigation_id:id})}); const d=await r.json(); if(r.ok) setOrdered(prev => prev.some(x => x.startsWith(`${d.name}:`) || x === d.name) ? prev : [...prev, `${d.name}: ${d.summary} ${d.interpretation}`]); else setError(d.detail); }
  async function complete() { if(!consultationId) return; const finalDiagnosis=window.prompt("Final diagnosis:") || ""; const management=(window.prompt("Management plan (comma-separated):") || "").split(",").map(v=>v.trim()).filter(Boolean); const r=await fetch(`${API}/consultations/${consultationId}/complete`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({final_diagnosis:finalDiagnosis,management_plan:management})}); const d=await r.json(); if(r.ok) setReport(d); else setError(d.detail); }
  return <main><header><p className="eyebrow">Fictional educational simulation — not for real patient diagnosis</p><h1>AI Virtual Patient</h1><p>Practice structured clinical consultations with a case-grounded simulated patient.</p></header>
    {!selected ? <section className="grid">{cases.map(c => <article key={c.id}><p className="tag">{c.specialty} · {c.difficulty}</p><h2>{c.title}</h2><p>{c.presenting_complaint}</p><button disabled={loading} onClick={() => start(c)}>Start consultation</button></article>)}</section> : <section className="consultation"><div><button className="back" onClick={() => { stopBrowserLive(); socket.current?.close();setSelected(null);setConsultationId(null); }}>← Cases</button><h2>{selected.title}</h2><p>{selected.presenting_complaint}</p><p className="status">Vaani call: <strong>{callStatus}</strong></p><section className="browser-live"><h3>Free browser live demo</h3><p className="muted">Chrome + headphones recommended. This uses browser speech APIs; no phone number or Vaani credits.</p><button onClick={browserLive ? stopBrowserLive : startBrowserLive} disabled={!!report}>{browserLive ? "Stop browser live demo" : "Start browser live demo"}</button><span className="live-state">{browserLive ? (listening ? "Listening" : "Restarting microphone") : "Off"}{patientSpeaking ? " · Patient speaking" : ""}</span></section><div className="call-control"><input value={phoneNumber} onChange={e=>setPhoneNumber(e.target.value)} placeholder="Patient phone (+14155552671)"/><button onClick={dispatchCall} disabled={loading || !!report}>Start Vaani call</button></div><div className="transcript">{turns.length === 0 && <p className="muted">Start browser live demo, ask a question, or type your first history question.</p>}{turns.map((t,i)=><p key={i} className={t.role}><strong>{t.role === "learner" ? "You" : "Patient"}:</strong> {t.text}</p>)}</div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask a clinical history question…" disabled={loading || !!report}/><button type="button" className="voice" onClick={captureVoice} disabled={loading || !!report}>🎙 Dictate</button><button disabled={loading || !!report}>Send</button></form></div><aside><h3>Investigations / reports</h3>{investigations.map(item=><button key={item.id} onClick={()=>order(item.id)} disabled={!!report}>{item.name}</button>)}{ordered.map((item,i)=><p className="result" key={i}>{item}</p>)}<button className="complete" onClick={complete} disabled={!!report}>Complete consultation</button></aside></section>}
    {report && <section className="report"><h2>Evaluation — {report.overall_score}/100</h2><div className="scores">{Object.entries(report.scores).map(([key,value])=><p key={key}><strong>{key.replace("_"," ")}</strong><span>{value}</span></p>)}</div><h3>Strengths</h3><ul>{report.strengths.map(x=><li key={x}>{x}</li>)}</ul><h3>Missed items</h3><ul>{report.missed_items.map(x=><li key={x}>{x}</li>)}</ul><p>{report.feedback}</p></section>}
    {error && <p className="error">{error}</p>}</main>;
}
